### ISSUE TITLE
Feb 4th -> Forward.JS edition

### ISSUE THREAD

**Issue by MylesBorins** [dancejs/sf#1]
Moving the conversation over from https://github.com/dancejs/Oakland/issues/7

@bcoe @gsilk @nexxy @ceejbot would you like to play?
@othiym23 you had volunteered for sound engineering duties + a potential DJ slot.

Due to this event following a day of talks I think that it makes sense to treat it as mostly a dance party, and not program talks.  This will simplify the setup (unless we want to be doing projections).

@drnugent you mentioned that we have a room reserved and that we have A/V equipment.  Is that a full sound system?  Should we still be bringing monitors or a sub?

@mikeal do you have any thoughts?

**Comment by MylesBorins** [comment]
Also what do we want to do regarding lighting + robots?

**Comment by drnugent** [comment]
@TheAlphaNerd Right now it's a standard screen/projector/audio setup, but we can bring additional equipment if you need it. Ditto with lighting/robots; just let me know. 

I have another programming possibility, let me know what you think of this. One of our 501(c)3 beneficiary organizations is a group of drag queens who raise money for lgbtq college scholarships. They've offered to help put on a show, if you can work them into the program.

**Comment by affinity-matrix** [comment]
I would be happy to help however I can :) I actually have the ability to do more than play Spotify now, too!

**Comment by gsilk** [comment]
@TheAlphaNerd yes, I'd love to! I can also volunteer my transportation super-powers (ie, Sprinter van) and I'd also like to help @othiym23 on sound engineering duties so I can absorb some knowledge

**Comment by bcoe** [comment]
@TheAlphaNerd if there's room for me, I'd happily do a short set. I'd actually be interested in giving a 10 minute lightning talk on [record-crate](https://github.com/bcoe/record-crate), a music organization app I've been working on, leading into a set :+1:

**Comment by bcoe** [comment]
CC: @gsilk @TheAlphaNerd @mikeal @nexxy, @othiym23 

If there's already a good sound-system on site, I think it would be good to rein in the amount of equipment we bring, I know I'm still recovering from the amount of orchestration Dance.js JSFest took. Having said this! I think it might be smart to at least bring:
- a subwoofer.
- some of our lighting equipment (perhaps @nexxy would be interested in doing something with Spark?).
- @TheAlphaNerd we all love the robot, do we have the $350 budget for it?
- @TheAlphaNerd is there an opportunity to sound-check some time in January so that we can gauge what equipment we need to bring to round out the stereo?

**Comment by drnugent** [comment]
@nexxy @bcoe Would one/both of you be interested in giving the presentation during the main event in the afternoon? We have a short slot that opened due to a cancellation.

@bcoe I can request a subwoofer and cover the robot budget. Would you like an equipment list that the A/V vendor will provide?

**Comment by bcoe** [comment]
@drnugent @othiym23 @TheAlphaNerd, I would definitely be curious in an equipment list (and I think a subwoofer is a must), but I think a sound-check is the most important part :+1: 

Should I intro you to the [robot dance party](http://robotdanceparty.org/)? what email should I use for this?

How long are the talks? The talk I have in mind is fairly short, and I think would make more sense prior to my set. @nexxy has an awesome talk on the [cerulean](]https://github.com/nexxy/cerulean) which was given at the first Dance.js, @gsilk also has a live-coding music demo which he's been working on.

**Comment by gsilk** [comment]
I'd be happy to give a more refined lightning round version of the talk I gave at the last DanceJS.

**Comment by mikeal** [comment]
One thing to keep in mind is that the majority of our equipment is being installed semi-permanently in the new event space in Oakland. That doesn't mean it's impossible to transport but I don't want to be pulling up all the cables that are gaffed and re-running them a couple times a month.

If we want to be able to easily transport everything we'll need to invest in a second set of cables at the least. Some of the lighting may not be permanently installed so that could go, but it's going to be a lot of work to move all this stuff once it's setup and we're likely to lose or accidentally steal things (i've already found a few power strips marked "25C" I need to give back).

**Comment by MylesBorins** [comment]
I think that equipment is being supplied for this event Fwiw

**Comment by drnugent** [comment]
Currently we've got two 12" speakers + cables, a small mixer, a projector and an 8' screen. I know we need to add a subwoofer; let me know what else to add. I'd like the A/V guys to set up as much as possible so you don't have to worry about lugging equipment/taking up cables.

**Comment by drnugent** [comment]
WRT talks: we can give you a 30m slot from 5:30p-6p, or you can give the talks starting at 6p in the dance room. I imagine you'd want to give all the talks starting at 6p? LMK if I'm mistaken.

**Comment by MylesBorins** [comment]
What is the timeline that we are imagining for the dance party?  is 5:30 - 6:00 the time people are being given to grab dinner?

It sounds to me like the set up has everything we need.  Some lights might be nice, but not necessary.=

**Comment by drnugent** [comment]
5:30p-6:00p is the last session of the day, I was thinking we'd have the dance party, drinks and light snacks from 6:00p-8:00p, and people can peel off to get dinner at any time they like. What do you think @TheAlphaNerd? And what kind of lights can we set up?

**Comment by MylesBorins** [comment]
That timing sounds very reasonable to me.  For some reason I was imagining the dance party happening a bit later, but 6 - 8 definitely works.

In the past we have had a handful of dmx dj lights that are sound reactive setup around the venue @nexxy where do those usually come from?=

**Comment by drnugent** [comment]
Aww right everything is coming together all awesome-like. We're going to bring in an outside vendor to set up the sound system because the hotel is afraid of DJs. Email is out to the robot dance party. Drag queens will be selling drink tickets during the party to raise money for queer youth scholarships. Attempting to confirm a photo booth. We'll try to get everything set up a few hours before the party so you can do a sound check, and then the party runs from 6p-9p.

@emilyrose @gsilk @bcoe may I add you as presenters to the main site? If you can drop me your email address I'll also send you codes for tickets for two friends: drnugent@gmail. Also @emilyrose what lights would you recommend?

**Comment by MylesBorins** [comment]
@emilyrose @gsilk @bcoe are you all planning to speak or just perform?

Depending on timing I have content that I could do a lighting talk on if time permits.  I also think it would be a good idea to solidify performance.

It doesn't look to me like we made a decision regarding running the talks at the last slot vs. at 6pm.  I'm airing on the side of having the lighting talks in the same space as the dance party so that we don't have to bounce between multiple spaces right before the event.

Thoughts?

**Comment by drnugent** [comment]
@TheAlphaNerd Oh yeah, the talks will be in the dance party space. The only thing I'm curious about is whether we will be doing the talks up front, and then the DJ sets, or talk/set/talk/set/talk/set. If it's the latter, how do we get everyone to be quiet for the talk?

**Comment by MylesBorins** [comment]
I think that we could have talks end with @gsillk who’s talk would turn into a performance.

@nexxy did you want to present your keyboard project?
@bcoe what topic were you considering?

I was thinking about discussing the difference between analogue and digital.  Explaining sample rates, bit rates, and why 44.1 k (dat nyquist limit)=

**Comment by affinity-matrix** [comment]
@TheAlphaNerd I am happy to do a brief presentation & demo on [cerulean](https://github.com/emilyrose/cerulean) if you like :)

I'm also prepared to fill some time with mindless remixes of pop songs if necessary!

**Comment by bcoe** [comment]
Hey, same as @emilyrose, I'd be happy to talk or DJ.

I have a talk in mind regarding mixing music using Node.js Streams/unit-generators: https://github.com/bcoe/unitgen

@othiym23 just got a new mixer, and I know he'd love to perform; perhaps we could come up with a tentative schedule soon so that we know everyone's responsibilities.

I'd be flattered to be added as a presenter, I'm sure I'll end up doing something, my email is ben@npmjs.com.

**Comment by drnugent** [comment]
We just had a 10-15m slot open up earlier in the day. What does everyone think of:
2:45p-3p: @emilyrose and @bcoe present
6p: @TheAlphaNerd, @gsilk present
~6:15p: @gsilk performance
Through 9p: Everyone else performs

Thoughts?

**Comment by bcoe** [comment]
@drnugent works for me, I can my demo a very short fun demo :+1:, followed by overtly plugging Dance.js.

**Comment by bcoe** [comment]
@drnugent @TheAlphaNerd when you have a second, perhaps update the dance.js repo with the details for the event?

I've been moving past events into an archives folder, like so:

http://dancejs.io/2014/10/04

**Comment by drnugent** [comment]
I just called for some A/V quotes and it sounds like the subwoofer will add about $1,000 because a tech will need to be on-hand for the whole event. Is it possible to buy our own subwoofer and hook it into the existing system?

**Comment by bcoe** [comment]
@drnugent, @mikeal has a subwoofer we should see if we can borrow it for the event.

**Comment by drnugent** [comment]
@mikeal that would be awesome if possible, but if it's too much work we're happy to buy one
